; HoneyBan filter: Apache/HTTPD auth failures

[apache-basic-auth]
enabled=on
syslog_identifier=apache2
prefilter=AH01617,authentication failure,user
ip_group=1
regex=\[client ([0-9A-Fa-f:.]+)(:[0-9]+)?\].*AH01617
regex=\[client ([0-9A-Fa-f:.]+)(:[0-9]+)?\].*authentication failure

[httpd-basic-auth]
enabled=on
syslog_identifier=httpd
prefilter=AH01617,authentication failure,user
ip_group=1
regex=\[client ([0-9A-Fa-f:.]+)(:[0-9]+)?\].*AH01617
regex=\[client ([0-9A-Fa-f:.]+)(:[0-9]+)?\].*authentication failure
