; HoneyBan filter: Dovecot auth failures

[dovecot-auth]
enabled=on
syslog_identifier=dovecot
prefilter=auth failed,Aborted login,rip=
ip_group=1
regex=auth failed.* rip=([0-9A-Fa-f:.]+)
regex=Aborted login.* rip=([0-9A-Fa-f:.]+)
regex=Disconnected \(auth failed.* rip=([0-9A-Fa-f:.]+)
