; HoneyBan filter: Exim auth failures

[exim-auth]
enabled=on
syslog_identifier=exim
prefilter=failed to authenticate,authentication failure,AUTH
ip_group=1
regex=failed to authenticate .* from [[]([0-9A-Fa-f:.]+)[]]
regex=authentication failure .* from [[]([0-9A-Fa-f:.]+)[]]
