; HoneyBan filter: nginx HTTP auth failures

[nginx-http-auth]
enabled=on
syslog_identifier=nginx
prefilter=basic authentication,password mismatch,user was not found
ip_group=1
regexi=user \"[^\"]+\": [^,]*, client: ([0-9A-Fa-f:.]+),?
regexi=no user/password was provided for basic authentication.* client: ([0-9A-Fa-f:.]+),?
