; HoneyBan filter: OpenVPN authentication and TLS failures

[openvpn-auth]
enabled=on
syslog_identifier=openvpn
prefilter=TLS Error,AUTH_FAILED,Authenticate/Decrypt packet error
ip_group=1
regex=([0-9A-Fa-f:.]+):[0-9]+ TLS Error
regex=from [[][A-Z_0-9]+[]]([0-9A-Fa-f:.]+):[0-9]+
regex=AUTH_FAILED.* from ([0-9A-Fa-f:.]+):[0-9]+
