; HoneyBan filter: Postfix SASL authentication failures

[postfix-sasl]
enabled=on
syslog_identifier=postfix/smtpd
prefilter=SASL,authentication failed
ip_group=1
regex=[[]([0-9A-Fa-f:.]+)[]]: SASL [A-Z0-9_-]+ authentication failed
regex=SASL [A-Z0-9_-]+ authentication failed.*[[]([0-9A-Fa-f:.]+)[]]
