; HoneyBan filter: ProFTPD auth failures

[proftpd-auth]
enabled=on
syslog_identifier=proftpd
prefilter=Login failed,no such user
ip_group=1
regex=USER .*[(]Login failed[)]: ([0-9A-Fa-f:.]+)
regex=no such user found from ([0-9A-Fa-f:.]+)
