; HoneyBan filter: Pure-FTPd auth failures

[pureftpd-auth]
enabled=on
syslog_identifier=pure-ftpd
prefilter=Authentication failed,Login failed
ip_group=1
regex=[(][^@]*@([0-9A-Fa-f:.]+)[)].*Authentication failed
regex=[(][^@]*@([0-9A-Fa-f:.]+)[)].*Login failed
