; HoneyBan filter: vsftpd auth failures

[vsftpd-auth]
enabled=on
syslog_identifier=vsftpd
prefilter=FAIL LOGIN,authentication failure
ip_group=1
regex=FAIL LOGIN: Client \"([0-9A-Fa-f:.]+)\"
regex=authentication failure.*from ([0-9A-Fa-f:.]+)
